### ISSUE TITLE
2 roms seems to have same content, maybe upload issue

### ISSUE THREAD

**Issue by DennisD2** [VintageProject/HP4952A#1]
These two ROM content files (U212 and U204) are equal. Maybe something went wrong during upload.

cmp PSU-CPU-CRT\ Board/U212_04952-10029_TMS27C256.BIN RAM-ROM\ Board/U204_04952-10029_TMS27C256.BIN

I intend to dump ROMs from my machine, if so, I will create a PR.... but may last some days

**Comment by DennisD2** [comment]
Meanwhile I have dumped both ROMs from my machine. They, in fact, have identical content.

This is kind of a mystery, because it looks like that ROM contains 68000 code, and a 68008 is only on RAM-ROM-Board, not on PSU-CPU-CRT board. 

One additional hint: The board that you mentioned as "Unknown Board" is in fact the Extended RAM Option board, it offers additional 128KB memory for saving analysis data. 

I will close the issue, if I am allowed to do that.
Thanks,
Dennis

**Comment by DennisD2** [comment]
and closed

**Comment by VintageProject** [comment]
Hey Dennis,
sorry for not responding earlier. It's a bit busy.

Thank you for checking on the ROM and your feedback!
I'll also update the texts with your input.
